---

name: rollout on release

on:
  release:
    types:
      - created

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: trigger deploy
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          user-token: ${{ secrets.CIRCLE_TOKEN }}
          project-slug: filecoin-project/lotus-infra
          branch: ${{ github.event.inputs.circle_branch }}
          payload: |
            {
              "override_tag": "${{ steps.get_version.VERSION }}",
              "slack_channel": "fil-infra-alerts"
            }
